dev:
  outputs:
    local:
      dremio_space: "@user"
      dremio_space_folder: no_schema
      object_storage_path: no_schema
      object_storage_source: lakehouse
      password: thaihunghp123
      port: 9047
      software_host: localhost
      threads: 1
      type: dremio
      use_ssl: false
      user: hungvt
    dev:
      dremio_space: "@user"
      dremio_space_folder: no_schema
      object_storage_path: no_schema
      object_storage_source: lakehouse
      password: thaihunghp123
      port: 9047
      software_host: dremio
      threads: 1
      type: dremio
      use_ssl: false
      user: hungvt
  target: local
