dremio_dbt:
  outputs:
    intermediate:
      object_storage_path: intermediate
      object_storage_source: lakehouse
      password: thaihunghp123
      port: 9047
      software_host: dremio
      threads: 1
      type: dremio
      use_ssl: false
      user: hungvt

    marts:
      object_storage_path: marts
      object_storage_source: lakehouse
      password: thaihunghp123
      port: 9047
      software_host: dremio
      threads: 1
      type: dremio
      use_ssl: false
      user: hungvt

  target: marts
