version: 2

sources:
  - name: lakehouse
    database: lakehouse
    schema: staging.db
    tables:
      - name: beneficiaries_iceberg
      - name: users_iceberg
      - name: wallets_iceberg
      - name: transactions_iceberg
      - name: notifications_iceberg
      - name: payment_methods
      - name: transaction_types
